# Exemple de fichier de configuration hardware pour un robot mécanum (chat GPT) modifié ensuite par Erudil

hardware_interfaces:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    joints:
      - roue_AvG_joint
      - roue_AvD_joint
      - roue_ArG_joint
      - roue_ArD_joint

  velocity_controllers:
    mecanum_wheel_fl_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: roue_AvG_joint
    mecanum_wheel_fr_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: roue_AvD_joint
    mecanum_wheel_rl_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: roue_ArG_joint
    mecanum_wheel_rr_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: roue_ArD_joint

  mecanum_drive_controller:
    type: differential_drive_controller/DifferentialDriveController
    left_wheel: [roue_AvG_joint, roue_ArG_joint]
    right_wheel: [roue_ArG_joint, roue_ArR_joint]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0] #Donnés par chatGPT -- se trouvent par l'expérience.
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0]
