<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

    <joint name="camera_joint" type="fixed">
        <origin xyz="0 ${base_length/2-camera_width} ${mecanum_radius+h_AxeMoteur_Base+base_thickness+tiges_length-camera_thickness/2}" rpy="0 0 0"/>
        <parent link="plateau2_link"/>
        <child link="camera_link"/>        
    </joint>
    
    
    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_thickness}" />
            </geometry>
            <material name="blue" />
        </visual>
        <visual>
            <origin xyz="0 ${camera_width/2+camera_obj_length/2} 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder length="${camera_obj_length}" radius="${camera_obj_radius}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0.0 0 0" rpy="0 0 0"/> <!-- attention j'ai rien modif Ã  partir de la -->
            <geometry>
                <box size="${camera_length} ${camera_width+camera_obj_length} ${camera_thickness}" />
            </geometry>
        </collision>

        <xacro:inertial_box mass="${camera_mass}" x="${camera_length}" y="${camera_width}" z="${camera_thickness}">
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference='camera_link'>
        <material>Gazebo/Blue</material>
    </gazebo>



</robot>