<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- LiDAR Joint -->
        <joint name="LiDAR_joint" type="fixed">
            <parent link="base_link"/>
            <child link="LiDAR_link"/>
            <origin xyz="0 0 ${mecanum_radius+h_AxeMoteur_Base+LiDAR_length/2}" rpy="0 0 0"/>               
        </joint>
        
        <!-- LiDAR Link -->
        <link name="LiDAR_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>               
                <geometry>
                    <cylinder length="${LiDAR_length}" radius="${LiDAR_radius}"/> <!-- dimensions -->
                </geometry>
                <material name="yellow"/>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>               
                <geometry>
                    <cylinder length="${LiDAR_length}" radius="${LiDAR_radius}"/> <!-- dimensions -->
                </geometry>
            </collision>
            
            <xacro:inertial_cylinder mass="${LiDAR_mass}" length="${LiDAR_length}" radius="${LiDAR_radius}">
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <!-- Simulation du LiDAR -->
        <gazebo reference='LiDAR_link'>
            <material>Gazebo/Yellow</material>
            <sensor name="laser" type="ray">
                <pose> 0 0 0 0 0 0 </pose>
                <visualize>true</visualize>
                <update_rate>10</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>360</samples>
                            <resolution>1</resolution>
                            <min_angle>-3.14</min_angle>
                            <max_angle>3.14</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.3</min>
                        <max>12</max>
                        <resolution>0.01</resolution>
                    </range>
                </ray>
                <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <argument>~/out:=scan</argument> <!-- publishing ont the topic scan -->
                    </ros>
                    <output_type>sensor_msg/LaserScan</output_type>
                </plugin>
            </sensor>
        </gazebo>
</robot>
