<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
        <!-- LiDAR Joint -->
        <joint name="LiDAR_joint" type="fixed">
            <parent link="base_link"/>
            <child link="LiDAR_link"/>
            <origin xyz="0 0 ${mecanum_radius+h_AxeMoteur_Base+LiDAR_length/2}" rpy="0 0 0"/>               
        </joint>
        
        <!-- LiDAR Link -->
        <link name="LiDAR_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>               
                <geometry>
                    <cylinder length="${LiDAR_length}" radius="${LiDAR_radius}"/> <!-- dimensions -->
                </geometry>
                <material name="yellow"/>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>               
                <geometry>
                    <cylinder length="${LiDAR_length}" radius="${LiDAR_radius}"/> <!-- dimensions -->
                </geometry>
            </collision>
            
            <xacro:inertial_cylinder mass="${LiDAR_mass}" length="${LiDAR_length}" radius="${LiDAR_radius}">
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference='LiDAR_link'>
            <material>Gazebo/Yellow</material>
        </gazebo>
</robot>
